service: lambda-php-8-features

provider:
  name: aws
  region: eu-west-1
  runtime: provided
  deploymentBucket:
    name: env(DEPLOYMENT_BUCKET)
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

plugins:
  - ./vendor/bref/bref

functions:
  lambda:
    handler: index.php
    timeout: 30
    layers:
      - ${bref:layer.php-80}

package:
  exclude:
    - '**'
  include:
    - 'src/**'
    - 'vendor/**'
    - 'index.php'
